apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.redis
  version: v1
  metadata:
    - name: redisHost
      value: localhost:6379
    - name: redisPassword
      value: ""
    - name: consumerID
      value: gateway-api
    - name: enableTLS
      value: false
    - name: maxRetries
      value: 5
    - name: maxRetryBackoff
      value: "5s"
    - name: failureThreshold
      value: 3
    - name: processingTimeout
      value: "60s"
    - name: redeliverInterval
      value: "30s"
    - name: concurrency
      value: 10
scopes:
  - gateway-api 