apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: telemetry-subscription
spec:
  topic: spans
  route: /api/telemetry/spans
  pubsubname: telemetry-pubsub
  metadata:
    rawPayload: "true"
scopes:
  - gateway-api