name: CI

on:
  push:
    branches:
      - main # Changed from master to main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - run: yarn install --frozen-lockfile

      # Use the correct base branch for affected commands
      - name: Get base branch for affected commands
        id: get-base-branch
        run: |
          DEFAULT_BRANCH=$(git remote show origin | grep 'HEAD branch' | cut -d' ' -f5)
          echo "BASE_BRANCH=$DEFAULT_BRANCH" >> $GITHUB_ENV

      # Nx Affected runs only tasks affected by the changes in this PR/commit
      - run: yarn nx affected -t lint test build --base=$BASE_BRANCH --head=HEAD
